# SPDX-FileCopyrightText: Copyright (c) 2020 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
AllCops:
  Exclude:
    - 'assets/**/*'
    - 'vendor/**/*'
  DisplayCopNames: true
  TargetRubyVersion: 2.3
  SuggestExtensions: false
  NewCops: enable
Metrics/LineLength:
  Max: 100
Layout/EndOfLine:
  EnforcedStyle: lf
Style/MultilineTernaryOperator:
  Enabled: false
Metrics/BlockLength:
  Max: 60
Layout/ParameterAlignment:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
require:
  - rubocop-rake
  - rubocop-minitest
  - rubocop-performance
