docker:
  image: yegor256/rultor-image:1.22.0
assets:
  rubygems.yml: yegor256/home#assets/rubygems.yml
install: |
  sudo usermod -a -G rvm "$(whoami)"
  sudo apt install -y aspell
  pdd -f /dev/null
  bundle install --no-color "--gemfile=$(pwd)/Gemfile"
release:
  script: |-
    bundle exec rake
    sed -i "s/0\.0\.0/${tag}/g" bin/texsc
    sed -i "s/0\.0\.0/${tag}/g" texsc.gemspec
    git add bin/texsc
    git add texsc.gemspec
    git commit -m "version set to ${tag}"
    gem build texsc.gemspec
    chmod 0600 ../rubygems.yml
    gem push *.gem --config-file ../rubygems.yml
merge:
  script: |-
    bundle exec rake
