assets:
  rubygems.yml: yegor256/home#assets/rubygems.yml
install: |
  pdd -f /dev/null
  sudo bundle install --no-color "--gemfile=$(pwd)/Gemfile"
release:
  script: |-
    bundle exec rake
    sed -i "s/0\.0\.0/${tag}/g" bin/texsc
    sed -i "s/0\.0\.0/${tag}/g" texsc.gemspec
    git add bin/texsc
    git add texsc.gemspec
    git commit -m "version set to ${tag}"
    gem build texsc.gemspec
    chmod 0600 ../rubygems.yml
    gem push *.gem --config-file ../rubygems.yml
merge:
  script: |-
    bundle exec rake
deploy:
  script: |-
    echo "There is nothing to deploy"
    exit -1
