---
name: codecov
on:
  push:
    branches:
      - master
jobs:
  codecov:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - run: sudo apt-get -y install aspell
      - run: bundle update
      - run: bundle exec rake
      - uses: codecov/codecov-action@v4.0.0-beta.3
        with:
          file: coverage/.resultset.json
          fail_ci_if_error: true
