---
name: rake
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    name: test
    strategy:
      matrix:
        os: [ubuntu-20.04]
        ruby: [2.7, 3.1]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: sudo apt-get -y install aspell
      - run: bundle update
      - run: bundle exec rake
